server:
  port: 8085
token:
  host: localhost
  expiration: 45
kafka:
  server: localhost:9092
  producer:
    id: identityProducer

key:
  privateKeyPath: classpath:keys/private_key.der

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/master.xml